services:
    mariadb_express:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r!
            MYSQL_DATABASE: community_board_express
            MYSQL_USER: codeplay_user
            MYSQL_PASSWORD: codeplay123
        ports:
            - "3307:3306"
        volumes:
            - ./:/docker-entrypoint-initdb.d # SQL 및 스크립트 파일이 이 디렉토리로 복사됨

    mariadb_nest:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r!
            MYSQL_DATABASE: community_board_nest
            MYSQL_USER: codeplay_user
            MYSQL_PASSWORD: codeplay123
        ports:
            - "3308:3306"
        volumes:
            - ./:/docker-entrypoint-initdb.d # SQL 및 스크립트 파일이 이 디렉토리로 복사됨
